name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is secret=${{secrets.TEST_SECRET}}"
      - uses: actions/checkout@v3
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
